kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../k8s
#- secret.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: global-env-vars
  behavior: replace
  envs:
    - shared-vars

images:
- name: gcr.io/ping-gte/bxfinanceapp
  newName: gcr.io/ping-gte/bxfinanceapp-dev

namespace: bxfinance-dev

namePrefix: ${REF_PREFIX}

commonLabels:
  refs: ${REF}

patches:
- target:
    kind: Deployment
    name: bxfinanceapp
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/stdin
      value: true
- target:
    kind: Deployment
    name: bxfinanceapp
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/tty
      value: true