kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../k8s
- admin-ingress.yaml
- namespace.yaml
- devops-secret.yaml
- gcr-pull-secret.yaml
- licenses.yaml
#- secret.yaml

generatorOptions:
  disableNameSuffixHash: true

images:
- name: gcr.io/ping-gte/bxfinanceapp
  newName: gcr.io/ping-gte/bxfinanceapp-dev

namespace: ${K8S_NAMESPACE}


commonLabels:
  refs: ${REF}

patches:
- target:
    kind: Deployment
    name: bxfinanceapp
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/stdin
      value: true
- target:
    kind: Deployment
    name: bxfinanceapp
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/tty
      value: true