# vars to set:
# export K8S_NAMESPACE=
# export EKS_USER=

# envsubst <  | kubectl apply -f -


apiVersion: v1
kind: Namespace
metadata:
  name: ${K8S_NAMESPACE}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bx-namespace-access
  namespace: ${K8S_NAMESPACE}
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bx-namespace-access-binding
  namespace: ${K8S_NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bx-namespace-access
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: devops-eks-rlyle
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: devops-eks-samirgandhi
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: devops-eks-michaelsanchez
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: devops-eks-kristinasalgado