version: "3"

services:
  pingfederate:
    image: pingidentity/pingfederate:10.2.0-edge
    command: wait-for pingdirectory:389 -t 520 -- entrypoint.sh start-server
    env_file:
      - ~/.pingidentity/devops
      - ./env_vars
    environment:
    - SERVER_PROFILE_URL=https://github.com/Technical-Enablement-PingIdentity/BXFinance.git
    - SERVER_PROFILE_PATH=pingfederate
    ports:
      - 9031:9031
      - 9999:9999

  pingdirectory:
    image: pingidentity/pingdirectory:8.2.0.0-edge
    env_file:
      - ~/.pingidentity/devops
      - ./env_vars
    environment:
      - SERVER_PROFILE_URL=https://github.com/Technical-Enablement-PingIdentity/BXFinance.git
      - SERVER_PROFILE_PATH=pingdirectory
    ports:
      - 389:389
      - 1636:636
      - 1443:443
      - 2443:2443
  
  pingdataconsole:
    image: pingidentity/pingdataconsole:latest
    ports:
      - 8080:8080
      - 8443:8443
  
  pingaccess:
    image: pingidentity/pingaccess:6.2.0-edge
    command: wait-for pingfederate:9999 -t 900 -- entrypoint.sh start-server
    env_file:
     - ~/.pingidentity/devops
     - ./env_vars
    environment:
     - SERVER_PROFILE_URL=https://github.com/Technical-Enablement-PingIdentity/BXFinance.git
     - SERVER_PROFILE_PATH=pingaccess
    ports:
     - 80:8080
     - 443:3000
     - 9000:9000

  pingdelegator:
    image: pingidentity/pingdelegator:edge
    environment: 
      - VERBOSE=true
    env_file:
     - ./env_vars
    ports:
     - 6080:6080

  pingdatapap:
    image: pingidentity/pingdatagovernancepap:2012-8.2.0.0
    env_file:
      - ~/.pingidentity/devops
      - ./env_vars
    environment:
      - SERVER_PROFILE_URL=https://github.com/Technical-Enablement-PingIdentity/BXFinance.git
      - SERVER_PROFILE_PATH=pingdatagovernancepap
      - PING_IDENTITY_ACCEPT_EULA=YES
      - REST_API_HOSTNAME=pingdatapap
      - HTTPS_PORT=9443
      - DECISION_POINT_SHARED_SECRET=2Federate
    ports:
      - 9443:9443

  pingdatagovernance:
    image: pingidentity/pingdatagovernance:2012-8.2.0.0 
    env_file:
      - ~/.pingidentity/devops
      - ./env_vars
    command: wait-for pingfederate:9031 -t 720 -- entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_URL=https://github.com/Technical-Enablement-PingIdentity/BXFinance.git
      - SERVER_PROFILE_PATH=pingdatagovernance
      - PING_IDENTITY_ACCEPT_EULA=YES
    ports:
      - 3443:443

  

  
