apiVersion: batch/v1
kind: Job
metadata:
  name: ${JOB_NAME}
  labels:
    role: ${JOB_NAME}
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        role: ${JOB_NAME}
    spec:
      containers:
      - image: postman/newman:alpine
        ### UPDATE COLLECTION ON NEXT LINE
        args: ["run", "https://www.getpostman.com/collections/${COLLECTION_ID}","--environment","/usr/src/app/global_postman_vars.json","--insecure", "--ignore-redirects", "--verbose"]
        imagePullPolicy: "IfNotPresent"
        name: ${JOB_NAME}
        volumeMounts:
        - mountPath: /usr/src/app/global_postman_vars.json
          name: global-env-vars-postman
          subPath: global_postman_vars.json
      restartPolicy: Never
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: global_postman_vars.json
            path: global_postman_vars.json
          name: global-env-vars-postman
        name: global-env-vars-postman